/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 scene.gltf --transform 
Files: scene.gltf [27.62KB] > C:\Users\risha\Desktop\natHacks\zenScape\zenscape\public\models\snowcabin\scene-transformed.glb [979.84KB] (-3448%)
Author: Shahriar Shahrabi (https://sketchfab.com/shahriyarshahrabi)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cabin-on-the-hill-7c6de91d44e14814be0297ce58af80f2
Title: Cabin on the hill
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'


import { useCameraAnimation } from './Zoom'

export function Model({ ...props }) {
  const { nodes, materials } = useGLTF('/scene-transformed.glb')
  const { startZoomAnimation, isAnimating } = useCameraAnimation();

  return (
    <group {...props} dispose={null}>
      <mesh 
        geometry={nodes.SnowParticles_SnowParticleTexture_0.geometry} 
        material={materials.SnowParticleTexture} 
        rotation={[-Math.PI / 2, 0, 0]} 
      />
    </group>
  )
}

useGLTF.preload('/scene-transformed.glb')
