/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Shahriar Shahrabi (https://sketchfab.com/shahriyarshahrabi)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cabin-on-the-hill-7c6de91d44e14814be0297ce58af80f2
Title: Cabin on the hill
*/

"use client";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

export default function SnowHut(props) {
  const { nodes, materials } = useGLTF(
    "/models/snowcabin/scene-transformed.glb"
  );
  const snowRef = useRef();
  useFrame((state, delta) => {
    snowRef.current.position.y -= (delta / 4) * 10;
    if (snowRef.current.position.y < -40) {
      snowRef.current.position.y = 0;
    }
  });

  return (
    <group
      {...props}
      dispose={null}
      scale={[0.1, 0.1, 0.1]}
      position={[0, -1.7, 0]}
      rotation={[0, -Math.PI / 2, 0]}
    >
      <mesh
        name="Trees_VertexColor_0"
        castShadow
        receiveShadow
        geometry={nodes.Trees_VertexColor_0.geometry}
        material={materials.VertexColor}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        name="Snow_SnowWithTexture_0"
        castShadow
        receiveShadow
        geometry={nodes.Snow_SnowWithTexture_0.geometry}
        material={materials.SnowWithTexture}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        ref={snowRef}
        name="SnowParticles_SnowParticleTexture_0"
        castShadow
        receiveShadow
        geometry={nodes.SnowParticles_SnowParticleTexture_0.geometry}
        material={materials.SnowParticleTexture}
        rotation={[-Math.PI / 2, 0, 0]}
        position={[0, 0, 0]}
      />
    </group>
  );
}

useGLTF.preload("/models/snowcabin/scene-transformed.glb");
